accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

goat_app/urls.py
from django.conf.urls import url
from goat_app import views

# TEMPLATE TAGGING
app_name = 'goat_app'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^gallery/', views.ImageList.as_view(), name='gallery'),
    url(r'^surprise/', views.surprise_goat, name='surprise_goat'),
    url(r'^goat/(?P<pk>\d+)/', views.ImageDetail.as_view(), name='detail'),
    url(r'^about/', views.about, name='about'),
    url(r'^ajax/validate_email/$', views.validate_email, name='validate_email'),
    url(r'^ajax/goat_vote/$', views.goat_vote, name='goat_vote'),
]

goat_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('goat_app.urls')),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^bye/", views.ByePage.as_view(), name="bye"),
    url(r"^welcome/", views.WelcomePage.as_view(), name="welcome"),
]

accounts/models.py
from django.contrib import auth
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

class Subscriber(models.Model):
    user = models.OneToOneField(get_user_model(), unique=True, on_delete=models.CASCADE)
    interest = models.CharField(max_length=20, null=False)

goat_app/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Daily_Image(models.Model):
    up_votes = models.IntegerField(default=0, null=False)
    down_votes = models.IntegerField(default=0, null=False)
    first_published_date = models.DateTimeField(default=timezone.now, null=False)
    pixa_id = models.PositiveIntegerField(null=False)
    pixa_url = models.URLField(null=False, max_length=100)
    pixa_user = models.CharField(null=False, max_length=255)
    image_path = models.ImageField(null=False, upload_to='daily_images', max_length=100, unique=True)

    def get_latest():
        return Daily_Image.objects.latest('first_published_date')

    def vote(has_liked, id):
        chosen = Daily_Image.objects.get(pk=id)
        print(has_liked)
        if(has_liked == True):
            print('up')
            chosen.up_votes = chosen.up_votes + 1
        else:
            print('down')
            chosen.up_votes = chosen.up_votes - 1
        chosen.save()
        return

    # TODO:
    # not yet used. Could be nice alternative to all the different file paths in settings
    @staticmethod
    def get_directory():
        return 'daily_images'

    def __str__(self):
        return self.image_path.url

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Subscriber
from django.contrib.auth import get_user_model
from django import forms

class UserCreateForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        # interest = Subscriber.interest
        fields = ("username", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"
        student_kwargs = kwargs.copy()
        self.subscriber_form = SubscriberForm(*args, student_kwargs)
        self.fields.update(self.subscriber_form.fields)
        # print('init', kwargs)

    def save(self, *args, **kwargs):
        user = super(UserCreateForm, self).save()
        subscriber = Subscriber.objects.create(user=user, interest=self.cleaned_data['interest'])
        subscriber.save()


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ("interest",)

accounts/views.py
from django.contrib.auth import login, logout, authenticate
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView
from django.http import HttpResponse
from . import forms
from django.shortcuts import render



class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("welcome")
    template_name = "accounts/signup.html"

    def form_valid(self, form):
        form.save()
        print('*'*50)
        username = self.request.POST['username']
        password = self.request.POST['password1']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return render(self.request, 'goat_app/index.html')

goat_app/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.core.mail import send_mail
from django.views.generic import ListView, DetailView
import os
from goat_website import settings
from goat_app.models import Daily_Image
from accounts.models import Subscriber
from accounts.forms import UserCreateForm
import random

# Create your views here.
def index(request):
    form = UserCreateForm
    return render(request, 'goat_app/index.html')

def gallery(request):
    # return render(request, 'goat_app/gallery.html', context={'images': getGoatImages()})
    return render(request, 'goat_app/gallery.html', context={'images': Daily_Image.objects.all()})

def about(request):
    return render(request, 'goat_app/about.html')

def surprise_goat(request):
    images = getGoatImages()
    image = images[random.randrange(0, len(images))]
    return render(request, 'goat_app/surprise_goat.html', context={'image': image})

def getGoatImages():
    images = []
    for f in os.listdir(os.path.join(settings.STATIC_DIR, "images/collection/")):
        images.append(os.path.join("images/collection/", f))
    return images

class ImageList(ListView):
    model = Daily_Image


class ImageDetail(DetailView):
    model = Daily_Image

    def get_object(self):
        # Call the superclass
        object = super().get_object()
        # Record the last accessed date
        if(object.first_published_date == Daily_Image.get_latest().first_published_date):
            object.votable = True
        # Return the object
        return object


def validate_email(request):
    email = request.GET.get('email', None)
    interest = request.GET.get('interest', None)
    data = {
        'is_taken': Subscriber.objects.filter(email__iexact=email).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'A user with this email already exists.'
    elif len(interest) != 1:
        data['interest_error'] = 'Please enter a single word without punctuation'
    else:
        new_subscriber = Subscriber(email = email)
        new_subscriber.save()
    return JsonResponse(data)

def goat_vote(request):
    has_liked = int(request.GET.get('hasLiked', None))
    id = request.GET.get('id', None)
    boolean_has_liked = True if (has_liked == 1) else False
    Daily_Image.vote(boolean_has_liked, id)
    return HttpResponse(status=204)

goat_website/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class ByePage(TemplateView):
    template_name = 'bye.html'

class WelcomePage(TemplateView):
    template_name = 'welcome.html'

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block body_block %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}
  {% block body_block %}
  <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" value="Sign Up" class="btn btn-default">
  </form>
  {% endblock %}

templates/base.html
{% load staticfiles %}
<html>
 <head>
   <meta charset="utf-8">
   <title></title>
   <!-- Latest compiled and minified CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
   <!-- Optional theme -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
   <!-- Latest compiled and minified JavaScript -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
 </head>
 <body>
     <nav class="navbar navbar-default navbar-static-top">
       <div class="container">
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           <!-- TODO: Fix logo position -->
             <a class="navbar-brand" href="{% url 'goat_app:index' %}"><img src="{% static "images/branding/goat.svg" %}" alt="Brand" height=30 width=30></a>
           </div>
             <div class="navbar-collapse collapse">
               <ul class="nav navbar-nav navbar-left">
               <li><a class="navbar-link" href="{% url 'goat_app:gallery' %}">Gallery</a></li>
               <li><a class="navbar-link" href="{% url 'goat_app:surprise_goat' %}">Surprise</a></li>
               </ul>
               <ul class="nav navbar-nav navbar-right">
                 {% if user.is_authenticated %}
                  <li><a class="navbar-link" href="{% url 'accounts:logout' %}">Logout</a></li>
    					   {% else %}
						      <li><a class="navbar-link" href="{% url 'accounts:login' %}">Log in</a></li>
						      <li><a class="navbar-link" href="{% url 'accounts:signup' %}">Sign up</a></li>
    						{% endif %}
               <li><a class="navbar-link" href="{% url 'goat_app:about' %}">About</a></li>
               </ul>
             </div>
         </div>
       </div>
     </nav>
     <div class="container">

       {% block body_block %}
         <!-- Extending templates can add content here -->
       {% endblock %}

     </div>
 </body>
</html>

templates/bye.html
{% extends "base.html" %}
  {% block body_block %}
  <p>See ya later</p>
  {% endblock %}

templates/email.html
<!DOCTYPE html>
<html>
  <body>
    <h1>Good morning :)</h1>
      {% load static %}
    <img src="cid:gotd.jpg" alt='couldnt find'/>
  </body>
</html>

templates/goat_app/about.html
<!DOCTYPE html>
{% extends "base.html" %}
  {% block body_block %}
    <p>Credit for goat branding image goes to <a href="https://thenounproject.com/smb11104/">Sydney Barrett</a> from the <a href="https://thenounproject.com">Noun Project</a></p>
  {% endblock %}

templates/goat_app/daily_image_detail.html
<!DOCTYPE html>
{% extends "base.html" %}
  {% block body_block %}

    {% load static %}
    <div class='jumbotron'>
    <img class="thumbnail" src="{% static daily_image.image_path.url %}" alt="failed to find" height=100% width=100% padding-bottom=10px>
    {% if daily_image.votable %}
    <div class="">
      <button type="button" class="btn btn-default btn-lg likebutton">
        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
      </button>
      <span id='likemessage'>
      {% if daily_image.up_votes == 0 %}
        No likes yet. Be the first to like it! </p>
      {% else %}
        {{daily_image.up_votes}} like(s)
      {% endif %}
    </span>
    </div>
    {% endif %}
    <script type="text/javascript">
      var hasLiked = false
      // var likebutton = document.getElementByClass('likebutton');
      // var likemessage = document.getElementByClass('likemessage');
      $(".likebutton").click(function(){
        var upvotes = {{daily_image.up_votes}}
        $(this).children().toggleClass("glyphicon-thumbs-down")
        if(!hasLiked){
          $('#likemessage').text(upvotes + 1 + ' like(s)')
          hasLiked = true
          }
        else {
          $('#likemessage').text(upvotes + ' like(s)')
          hasLiked = false
        }
        $.ajax({
          url: "{% url 'goat_app:goat_vote' %}",
          data: {'hasLiked': hasLiked ? 1:0, 'id': "{{ daily_image.id }}"},
          dataType: 'json',
          success: function () {
          }
        });
      })
    </script>
    </div>
  {% endblock %}

templates/goat_app/daily_image_list.html
<!DOCTYPE html>
{% extends "base.html" %}
  {% block body_block %}
    <h1>gallery</h1>
    {% load static %}
    {% for image in object_list %}
      <div class="col-lg-4 col-xs-6">
        <a href="/goat/{{ image.id }}"><img class="thumbnail" src="{% static image.image_path.url %}" alt="failed to find" height=280 width=320 padding-bottom=10px></a>
      </div>
    {% endfor %}

  {% endblock %}

templates/goat_app/gallery.html
<!DOCTYPE html>
{% extends "base.html" %}
  {% block body_block %}
    <h1>gallery</h1>
    {% for image in images %}
      {% load static %}
      <div class="col-lg-4 col-xs-6">
        <img class="thumbnail" src="{% static image.image_path.url %}" alt="failed to find" height=280 width=320 padding-bottom=10px>
      </div>
    {% endfor %}

  {% endblock %}

templates/goat_app/index.html
{% extends "base.html" %}
  {% block body_block %}
  <div class="jumbotron">
    <h1>Hello, world (of photos)!</h1>
    <p>Welcome to my wonderful world of goats{% if user.is_authenticated %} {{ user.get_username }}{% endif %}. This website is an
      opportunity for me to practice using django with bootstrap,
      whilst also sharing with the world some joy through the medium of goats and other lovely images.</p>

      {% if not user.is_authenticated %}

      <p>I'd like to invite you to sign up below for my newsletter which provides you with a gotd (goat of the day) every day.</p>
      <!-- TODO: connect button to a subscription screen, want this to be same page... therefore jquery etc? can django do this? -->
      <a class="btn btn-lg btn-primary" href="{% url 'accounts:signup' %}">Subscribe</a>
      {% endif %}

      <p>Enjoy :)</p>
  {% endblock %}

templates/goat_app/subscribe.html
<!-- The modal -->
<div class="modal fade" id="subscriptionModal" tabindex="-1" role="dialog" aria-labelledby="modalLabelSmall" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
          <h4 class="modal-title" id="modalLabelSmall">Subscribe here for daily goat photos</h4>
      </div>
      </script>
      <div class="modal-body">
        <form method="post" data-validate-email-url="{% url 'goat_app:validate_email' %}" id="submit_subscription">
          {% csrf_token %}
          <!-- check form without reload https://simpleisbetterthancomplex.com/tutorial/2016/08/29/how-to-work-with-ajax-request-with-django.html -->
            {{ form.as_p }}
            <!-- <span id="emailError" style="display: none;">You can only use alphabetic characters, hyphens and apostrophes</span> -->
            <!-- this approach looks better https://www.abidibo.net/blog/2015/11/18/modal-django-forms-bootstrap-4/ -->
            <p id='subcription_result'></p>
        <input type="submit" value="Submit" id='submit_button' />
      </form>

      <script>
        $('#subscriptionModal').on('shown.bs.modal', function() {
          $('#id_email').focus();
        })

        $("#submit_subscription").submit(function (e) {
          e.preventDefault();
          // console.log(email);
          var form = $("#id_email").closest("form");
          $.ajax({
            url: form.attr("data-validate-email-url"),
            data: form.serialize(),
            dataType: 'json',
            success: function (data) {
              if (data.is_taken) {
                var email = document.getElementById('id_email');
                var submit = document.getElementById('submit_button')
                email.setCustomValidity('This email is already taken');
                document.querySelector('#submit_subscription').reportValidity();
              }else if (data.interest_error) {
                var interest = document.getElementById('id_interest');
                interest.setCustomValidity(data.interest_error);
              }else{
                var email = document.getElementById('id_email');
                var interest = document.getElementById('id_interest');
                $('subscribe_submit').click()
                email.setCustomValidity('');
                interest.setCustomValidity('');
                $("#id_email").css("border", "green");
                $("#id_email").css("box-shadow", "0 0 10px green");
                $('#id_email').prop('disabled', true)
                $('#submit_button').val('Submitting...')
                $('#submit_button').prop('disabled', true)
                $('#subscribe_modal').attr('href', '#')
                $('#subscribe_modal').text('Thanks for subscribing')
                $('#subscribe_modal').removeAttr('data-target')
                setTimeout(function() {
                    $('#subscriptionModal').modal('hide');
                }, 800);
              }
            }
          });
          // form.click();
        });
        // required to remove the customvalidation error when user is changing input
        $("#id_email").keydown(function () {
          this.setCustomValidity('');
        });
        </script>
      </div>
    </div>
  </div>
</div>

templates/goat_app/surprise_goat.html
<!DOCTYPE html>
{% extends "base.html" %}
  {% block body_block %}
    {% load static %}
      <img class="thumbnail" src="{%static image %}" alt="failed to find" height=100% width=100% padding-bottom=10px>
  {% endblock %}

templates/welcome.html
{% extends "base.html" %}
  {% block body_block %}
  <p>Hi!</p>
  {% endblock %}